on:
  schedule:
    - cron: "10 5 * * *"
jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Create config.json
        run: echo 'TOKEN=${{ secrets.TOKEN }}' > .env

      - name: Install Dependencies
        run: pnpm install

      - name: Run Bot
        run: |
          pnpm run build
          timeout 10s pnpm run start || true

